### ISSUE TITLE
^T shortcut sends terminate event to wrong tab in multishell

### ISSUE THREAD

**Issue by MCJack123** [Ocawesome101/recrafted#3]
When holding down ^T to send a `terminate` event, the terminate event is sent to the wrong tab. (I noticed this while implementing #2.)

To reproduce:
1. Open a new tab with `bg shell`
2. Open a `lua` prompt or other interactive program in both tabs
3. Hold ^T in the first tab
4. Notice the `terminate` event goes to the second tab

![2022-08-18_16 36 12](https://user-images.githubusercontent.com/6236912/185490095-33772c4c-4d37-4bd3-a2b1-cdccb617b7b2.gif)

**Comment by Ocawesome101** [comment]
hmm.  i thought i'd implemented this correctly.

**Comment by Ocawesome101** [comment]
should be fixed now.
