### ISSUE TITLE
Custom _HOST value

### ISSUE THREAD

**Issue by tomodachi94** [Ocawesome101/recrafted#5]
I think setting `_G._HOST` to a Recrafted-specific value might be a good idea. Currently, the value is set to something like `ComputerCraft 1.100.9 (CraftOS-PC v2.7.1) (UnBIOS)`, as set by `unbios.lua`.

**Comment by tomodachi94** [comment]
Appears to be set in [`unbios.lua#L29`](https://github.com/Ocawesome101/recrafted/blob/primary/unbios.lua#L29). Should be a trivial change.

**Comment by Ocawesome101** [comment]
done through Recrafted's `bios.lua` rather than in UnBIOS, because Recrafted doesn't always run through UnBIOS.  EDIT: also because replacing UnBIOS's changes would allow UnBIOS to run inside itself - which is intentionally disallowed.

**Comment by SquidDev** [comment]
We're gonna end up in the same place user agents are, aren't we?

**Comment by Ocawesome101** [comment]
[definitely not.](https://webaim.org/blog/user-agent-string-history/)
