### ISSUE TITLE
Broken on CC: Tweaked 1.109.0

### ISSUE THREAD

**Issue by RuinTD** [Ocawesome101/recrafted#6]
Hello. Recrafted seems to be broken due to CC: Tweaked 1.109.0 updating to Lua 5.2

https://github.com/Ocawesome101/recrafted/blob/0dc3342578bac59f2c93c86f251e8731fe710a9d/data/computercraft/lua/rom/modules/main/rc/thread.lua#L14

![javaw_BNaXcufkzU](https://github.com/Ocawesome101/recrafted/assets/1149870/3436e67f-6951-4052-9c88-fde2dc8f69ba)

**Comment by Ocawesome101** [comment]
holy shit they finally did it

i will fix this soonish

**Comment by Ocawesome101** [comment]
just pushed a potential fix. @RuiNtD can you test?  if not i can in a few hours.

**Comment by RuiNtD** [comment]
> just pushed a potential fix. @RuiNtD can you test? if not i can in a few hours.

:)
![javaw_wMWA9pJSL0](https://github.com/Ocawesome101/recrafted/assets/1149870/38681458-10c7-4657-96ce-6bf5b20d0293)

**Comment by RuinTD** [comment]
:)
![image](https://github.com/Ocawesome101/recrafted/assets/1149870/1b8e73d7-e538-425e-9af7-7c4acc7c3828)

**Comment by Ocawesome101** [comment]
awesome! closing
